USE cmsmvc;

-- Insertar artículo sobre Goku Ultra Instinto
INSERT INTO novas (titulo, slug, extracto, texto, activo, home, datap, autor, imaxe) VALUES 
('Goku Ultra Instinto: La Maestría Suprema', 'goku-ultra-instinto-maestria-suprema', 'Goku alcanza el estado Ultra Instinto dominado, mostrando un poder sin precedentes en el universo Dragon Ball.', '<p>Goku ha alcanzado finalmente el dominio completo del Ultra Instinto, una técnica que le permite moverse y combatir de forma instintiva sin necesidad de pensar. Este estado representa el pináculo del poder martial en el universo Dragon Ball.</p><p>En su última batalla contra Jiren, Goku demostró que el Ultra Instinto no es solo una transformación, sino un estado de conciencia que trasciende los límites físicos y mentales. Cada movimiento es perfecto, cada esquivo es preciso y cada ataque tiene la máxima eficiencia.</p><p>Los expertos en artes marciales del universo describen este estado como "la perfección absoluta del combate", donde el cuerpo reacciona por sí solo a cualquier amenaza sin intervención consciente.</p>', 1, 1, NOW(), 'admin', 'goku_01.webp');

-- Insertar artículo sobre Bulma
INSERT INTO novas (titulo, slug, extracto, texto, activo, home, datap, autor, imaxe) VALUES 
('Bulma: La Genio Detrás de las Hazañas de los Guerreros Z', 'bulma-genio-detras-hazanas-guerreros-z', 'Bulma Briefs, la científica brillante que ha sido fundamental en todas las sagas de Dragon Ball.', '<p>Bulma Briefs es mucho más que la amiga de la infancia de Goku. Es una de las mentes más brillantes del universo Dragon Ball, responsable de crear tecnologías que han salvado al mundo en incontables ocasiones.</p><p>Desde el Dragon Radar original hasta las máquinas del tiempo, pasando por las cápsulas del tiempo y los avanzados sistemas de comunicación, Bulma ha sido el pilar tecnológico que ha permitido a los Guerreros Z enfrentar amenazas cada vez más poderosas.</p><p>Su inteligencia y capacidad para resolver problemas bajo presión la convierten en una pieza indispensable en el equipo. Sin sus inventos, muchas de las victorias de los Guerreros Z no habrían sido posibles.</p>', 1, 0, NOW(), 'admin', 'bulma.webp');
