USE cmsmvc;

-- Insertar 10 noticias con las imágenes nuevas (4 para home, 1 inactiva)

INSERT INTO novas (titulo, slug, extracto, texto, activo, home, datap, autor, imaxe) VALUES 
('Goku Ultra Instinto Dominado', 'goku-ultra-instinto-dominado', 'Goku alcanza el nivel más alto del Ultra Instinto, superando todos sus límites anteriores.', '<p>Goku ha alcanzado finalmente el dominio completo del Ultra Instinto, una técnica que le permite moverse y combatir de forma instintiva sin necesidad de pensar. Este estado representa el pináculo del poder martial en el universo Dragon Ball.</p><p>En su última batalla contra Jiren, Goku demostró que el Ultra Instinto no es solo una transformación, sino un estado de conciencia que trasciende los límites físicos y mentales. Cada movimiento es perfecto, cada esquivo es preciso y cada ataque tiene la máxima eficiencia.</p><p>Los expertos en artes marciales del universo describen este estado como "la perfección absoluta del combate", donde el cuerpo reacciona por sí solo a cualquier amenaza sin intervención consciente.</p>', 1, 1, NOW(), 'admin', 'goku_ultra.webp'),

('Vegeta Super Saiyan 4 Blue', 'vegeta-super-saiyan-4-blue', 'Vegeta fusiona el poder de Super Saiyan 4 con la energía divina Blue.', '<p>Vegeta ha logrado una transformación única que combina el poder del Super Saiyan 4 con la energía divina del Super Saiyan Blue. Esta nueva forma le otorga un poder sin precedientes que podría rivalizar incluso con el Ultra Instinto de Goku.</p><p>El príncipe de los Saiyajin ha entrenado intensamente bajo la tutela de Whis, perfeccionando su control sobre la energía divina mientras mantiene la ferocidad del Super Saiyan 4. El resultado es una transformación que equilibra perfectamente el poder bruto con la precisión divina.</p><p>"Nunca me quedaré atrás de Kakarot", declaró Vegeta tras alcanzar esta nueva forma. "Esta vez seré yo quien proteja a todos."</p>', 1, 1, NOW(), 'admin', 'vegeta_ss4.avif'),

('Black Goku: El Guerrero Oscuro', 'black-goku-guerrero-oscuro', 'Goku Black regresa con un poder aún mayor y planes destructivos.', '<p>Goku Black ha vuelto, pero esta vez con un poder que desafía toda lógica. Su última aparición en el universo ha causado pánico entre los guerreros Z, quienes recuerdan la devastación que causó en su anterior invasión.</p><p>Se desconoce cómo logró regresar, pero su poder parece haber aumentado significativamente. Los analistas especulan que podría haber encontrado una forma de fusionar su energía con el Time Ring de manera permanente.</p><p>"Esta vez no habrá segunda oportunidad", amenazó Black Goku. "Este universo será purgado por completo."</p>', 1, 1, NOW(), 'admin', 'black_goku.webp'),

('Cell Perfecto Evolucionado', 'cell-perfecto-evolucionado', 'Cell regresa con una nueva forma perfecta que supera incluso a los dioses.', '<p>El bioandroide Cell ha logrado una evolución inesperada tras absorber energía residual de batallas recientes. Su nueva "Perfecta Evolución" le otorga capacidades que rivalizan con las de los dioses de la destrucción.</p><p>Cell ha perfeccionado todas las técnicas de los guerreros que absorbió originalmente, añadiendo nuevas variaciones que lo hacen aún más peligroso. Su velocidad ha aumentado drásticamente, y su fuerza ahora supera los límites conocidos.</p><p>"Soy la forma de vida perfecta", proclamó Cell. "Nadie puede detenerme ahora."</p>', 1, 1, NOW(), 'admin', 'celula.webp'),

('Freezer Golden Max Power', 'freezer-golden-max-power', 'Freezer alcanza una nueva forma dorada que supera su transformación anterior.', '<p>El tirano Freezer ha entrenado secretamente en el otro mundo y ha logrado una evolución de su forma Golden que le otorga un poder comparable al de los Super Saiyan Blue.</p><p>Esta nueva forma, llamada "Golden Max Power", mantiene la elegancia dorada pero con una aura mucho más intensa y un poder multiplicado varias veces. Freezer afirma haber aprendido de sus errores anteriores.</p><p>"Esta vez no subestimaré a los Saiyajin", prometió Freezer. "El universo se arrodillará ante mí."</p>', 0, 0, NOW(), 'admin', 'frieza.webp'),

('Piccolo: El Guardián Definitivo', 'piccolo-guardian-definitivo', 'Piccolo alcanza un nuevo nivel de poder tras fusionarse con los Namekuseijin.', '<p>Piccolo ha realizado una fusión permanente con los Namekuseijin supervivientes, alcanzando un poder que le sitúa entre los guerreros más fuertes del universo. Su nueva forma le permite usar técnicas combinadas de todos los Namekuseijin.</p><p>Además de su aumento masivo de poder, Piccolo ha desarrollado nuevas habilidades como la "Regeneración Cuántica" que le permite recuperarse instantáneamente de cualquier daño.</p><p>"Protegeré la Tierra y a Gohan sin importar el costo", afirmó el ahora Namekuseijin definitivo.</p>', 1, 0, NOW(), 'admin', 'pikolo.webp'),

('Fusion Zamasas: La Amenaza Return', 'fusion-zamasas-amenaza-return', 'La fusión de Zamas y Goku Black regresa con planes universales.', '<p>La peligrosa fusión de Zamas y Goku Black ha logrado mantenerse estable gracias a una anomalía temporal. Ahora amenaza con expandir su "Cero Mortales" a todos los universos simultáneamente.</p><p>Los Time Rings han sido alterados de manera inesperada, permitiendo que esta fusión exista fuera del tiempo normal. Los guerreros Z deben encontrar una forma de detenerlo antes de que sea demasiado tarde.</p><p>"Todos los mortales serán eliminados", declaró la fusión. "Este es el juicio final."</p>', 1, 0, NOW(), 'admin', 'zaiko.webp'),

('Gohan Beast: La Nueva Bestia', 'gohan-beast-nueva-bestia', 'Gohan desbloquea su forma Beast con un poder superior al Ultra Instinto.', '<p>Gohan ha logrado controlar completamente su forma Beast, alcanzando un nivel de poder que sorprende incluso a los dioses. Esta transformación combina su potencial ilimitado con una ferocidad controlada.</p><p>Lo más impresionante es que Gohan puede mantener esta forma por períodos prolongados sin agotar su energía, algo que antes era imposible.</p><p>"Como padre y protector, nunca fallaré", dijo Gohan tras demostrar su nuevo poder en una sesión de entrenamiento.</p>', 1, 0, NOW(), 'admin', 'ss17.webp'),

('Broly Legendary Evolución', 'broly-legendary-evolucion', 'Broly controla su poder Legendary Super Saiyan con nueva precisión.', '<p>Broly ha aprendido a controlar su poder Legendary Super Saiyan, transformándolo de una fuerza destructiva en un poder preciso y controlado. Ahora puede luchar con total conciencia sin perder el control.</p><p>Su entrenamiento con Whis y Vegeta le ha enseñado a canalizar su ferocidad en técnicas específicas en lugar de estallidos destructivos.</p><p>"Quiero ser fuerte, pero no quiero destruir", explicó Broly. "Gracias a mis amigos, puedo controlar mi poder."</p>', 1, 0, NOW(), 'admin', 'flis.webp'),

('Goku Super Saiyan 2 Master', 'goku-super-saiyan-2-master', 'Goku perfecciona el Super Saiyan 2 a un nivel divino.', '<p>Goku ha redescubierto el Super Saiyan 2, elevándolo a un nivel que incorpora energía divina sin necesidad de transformaciones completas. Esta forma le permite un balance perfecto entre poder y consumo de energía.</p><p>Esta evolución del Super Saiyan 2 demuestra que incluso las formas clásicas pueden evolucionar cuando se combinan con conocimientos divinos.</p><p>"Cada transformación tiene su propósito", explicó Goku. "El Super Saiyan 2 es perfecto para ciertas batallas."</p>', 1, 0, NOW(), 'admin', 'goku_ss2.avif');
